### ISSUE TITLE
Suggestions for the chapter 1

### ISSUE THREAD

**Issue by raspberryenvoie** [demhademha/tweak-development-guide#4]
Hello @demhademha 
I found two tiny things in the first chapter that I think could be modified.

> [unc0ver, chimera and electra (devices not using the procursus bootstrap)](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-1.md#unc0ver-chimera-and--electra-devices-not-using-the-procursus-bootstrap)
[procursus based jailbreaks (odyssey, odysseyra1n)](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-1.md#procursus-based-jailbreaks-odyssey-odysseyra1n)

You could change the IP address to localhost like in the checkra1n section.

> [Connecting from a laptop over wifi](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-1.md#connecting-from-a-laptop-over-wifi) and [Using ssh over usb](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-1.md#using-ssh-over-usb)

You should maybe tell the reader to use the port 44 if he uses checkra1n otherwise the ssh connection will fail.

Let me know what you think of it :)
Have a nice day!

**Comment by demhademha** [comment]
I'll fix that soon hopefully 
Thanks for spotting that.

**Comment by raspberryenvoie** [comment]
Cool!

**Comment by demhademha** [comment]
Fixed in https://github.com/demhademha/tweak-development-guide/commit/49f730ab7b462fcf871a0a63004cc6f0d7264a69
Tell me if this is ready to close :)

**Comment by raspberryenvoie** [comment]
You forgot some small things, I made a new pull request https://github.com/demhademha/tweak-development-guide/pull/5
Let me know if it's okay

**Comment by demhademha** [comment]
Fixed in https://github.com/demhademha/tweak-development-guide/commit/24edaa2015b77d7cb7e7995b78908e1144f32be6
I'll leave this open for a bit in case you want to add anything.

**Comment by raspberryenvoie** [comment]
Okay, thanks, at the moment, I don't need to add anything

**Comment by demhademha** [comment]
Thank you for your contribution

**Comment by raspberryenvoie** [comment]
Np! I like the idea of this project, I’m sure this guide will help many people

**Comment by demhademha** [comment]
Well, if you want to be a **editor** send me a DM ;)
